// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: identity/identity.proto

package identity

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhoneType int32

const (
	PhoneType_PHONE_TYPE_UNSPECIFIED PhoneType = 0
	PhoneType_PHONE_TYPE_MOBILE      PhoneType = 1
	PhoneType_PHONE_TYPE_HOME        PhoneType = 2
	PhoneType_PHONE_TYPE_WORK        PhoneType = 3
)

// Enum value maps for PhoneType.
var (
	PhoneType_name = map[int32]string{
		0: "PHONE_TYPE_UNSPECIFIED",
		1: "PHONE_TYPE_MOBILE",
		2: "PHONE_TYPE_HOME",
		3: "PHONE_TYPE_WORK",
	}
	PhoneType_value = map[string]int32{
		"PHONE_TYPE_UNSPECIFIED": 0,
		"PHONE_TYPE_MOBILE":      1,
		"PHONE_TYPE_HOME":        2,
		"PHONE_TYPE_WORK":        3,
	}
)

func (x PhoneType) Enum() *PhoneType {
	p := new(PhoneType)
	*p = x
	return p
}

func (x PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_identity_proto_enumTypes[0].Descriptor()
}

func (PhoneType) Type() protoreflect.EnumType {
	return &file_identity_identity_proto_enumTypes[0]
}

func (x PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhoneType.Descriptor instead.
func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{0}
}

type FindPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPersonRequest) Reset() {
	*x = FindPersonRequest{}
	mi := &file_identity_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPersonRequest) ProtoMessage() {}

func (x *FindPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPersonRequest.ProtoReflect.Descriptor instead.
func (*FindPersonRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{0}
}

func (x *FindPersonRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PersonResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            int64                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                        `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones        []*PersonResponse_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonResponse) Reset() {
	*x = PersonResponse{}
	mi := &file_identity_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonResponse) ProtoMessage() {}

func (x *PersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonResponse.ProtoReflect.Descriptor instead.
func (*PersonResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{1}
}

func (x *PersonResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PersonResponse) GetPhones() []*PersonResponse_PhoneNumber {
	if x != nil {
		return x.Phones
	}
	return nil
}

type PersonResponse_PhoneNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PhoneType              `protobuf:"varint,1,opt,name=type,proto3,enum=grpc_example.identity.PhoneType" json:"type,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonResponse_PhoneNumber) Reset() {
	*x = PersonResponse_PhoneNumber{}
	mi := &file_identity_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonResponse_PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonResponse_PhoneNumber) ProtoMessage() {}

func (x *PersonResponse_PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonResponse_PhoneNumber.ProtoReflect.Descriptor instead.
func (*PersonResponse_PhoneNumber) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PersonResponse_PhoneNumber) GetType() PhoneType {
	if x != nil {
		return x.Type
	}
	return PhoneType_PHONE_TYPE_UNSPECIFIED
}

func (x *PersonResponse_PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

var File_identity_identity_proto protoreflect.FileDescriptor

const file_identity_identity_proto_rawDesc = "" +
	"\n" +
	"\x17identity/identity.proto\x12\x15grpc_example.identity\x1a\x1cgoogle/api/annotations.proto\"#\n" +
	"\x11FindPersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xf2\x01\n" +
	"\x0ePersonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12I\n" +
	"\x06phones\x18\x04 \x03(\v21.grpc_example.identity.PersonResponse.PhoneNumberR\x06phones\x1a[\n" +
	"\vPhoneNumber\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .grpc_example.identity.PhoneTypeR\x04type\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number*h\n" +
	"\tPhoneType\x12\x1a\n" +
	"\x16PHONE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PHONE_TYPE_MOBILE\x10\x01\x12\x13\n" +
	"\x0fPHONE_TYPE_HOME\x10\x02\x12\x13\n" +
	"\x0fPHONE_TYPE_WORK\x10\x032\x80\x01\n" +
	"\x0fIdentityService\x12m\n" +
	"\x04Find\x12(.grpc_example.identity.FindPersonRequest\x1a%.grpc_example.identity.PersonResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/person/{id}B\x13Z\x11protogen/identityb\x06proto3"

var (
	file_identity_identity_proto_rawDescOnce sync.Once
	file_identity_identity_proto_rawDescData []byte
)

func file_identity_identity_proto_rawDescGZIP() []byte {
	file_identity_identity_proto_rawDescOnce.Do(func() {
		file_identity_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_identity_proto_rawDesc), len(file_identity_identity_proto_rawDesc)))
	})
	return file_identity_identity_proto_rawDescData
}

var file_identity_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_identity_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_identity_identity_proto_goTypes = []any{
	(PhoneType)(0),                     // 0: grpc_example.identity.PhoneType
	(*FindPersonRequest)(nil),          // 1: grpc_example.identity.FindPersonRequest
	(*PersonResponse)(nil),             // 2: grpc_example.identity.PersonResponse
	(*PersonResponse_PhoneNumber)(nil), // 3: grpc_example.identity.PersonResponse.PhoneNumber
}
var file_identity_identity_proto_depIdxs = []int32{
	3, // 0: grpc_example.identity.PersonResponse.phones:type_name -> grpc_example.identity.PersonResponse.PhoneNumber
	0, // 1: grpc_example.identity.PersonResponse.PhoneNumber.type:type_name -> grpc_example.identity.PhoneType
	1, // 2: grpc_example.identity.IdentityService.Find:input_type -> grpc_example.identity.FindPersonRequest
	2, // 3: grpc_example.identity.IdentityService.Find:output_type -> grpc_example.identity.PersonResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identity_identity_proto_init() }
func file_identity_identity_proto_init() {
	if File_identity_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_identity_proto_rawDesc), len(file_identity_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_identity_proto_goTypes,
		DependencyIndexes: file_identity_identity_proto_depIdxs,
		EnumInfos:         file_identity_identity_proto_enumTypes,
		MessageInfos:      file_identity_identity_proto_msgTypes,
	}.Build()
	File_identity_identity_proto = out.File
	file_identity_identity_proto_goTypes = nil
	file_identity_identity_proto_depIdxs = nil
}
